# -*- coding: utf-8 -*-
#Should be string
compilation_timelimit = u"10"
timeout_return_code = 124

html_colors = {
    'ALICEBLUE': '{HTML}{F0F8FF}',
    'ANTIQUEWHITE': '{HTML}{FAEBD7}',
    'AQUA': '{HTML}{00FFFF}',
    'AQUAMARINE': '{HTML}{7FFFD4}',
    'AZURE': '{HTML}{F0FFFF}',
    'BEIGE': '{HTML}{F5F5DC}',
    'BISQUE': '{HTML}{FFE4C4}',
    'BLACK': '{HTML}{000000}',
    'BLANCHEDALMOND': '{HTML}{FFEBCD}',
    'BLUE': '{HTML}{0000FF}',
    'BLUEVIOLET': '{HTML}{8A2BE2}',
    'BROWN': '{HTML}{A52A2A}',
    'BURLYWOOD': '{HTML}{DEB887}',
    'CADETBLUE': '{HTML}{5F9EA0}',
    'CHARTREUSE': '{HTML}{7FFF00}',
    'CHOCOLATE': '{HTML}{D2691E}',
    'CORAL': '{HTML}{FF7F50}',
    'CORNFLOWERBLUE': '{HTML}{6495ED}',
    'CORNSILK': '{HTML}{FFF8DC}',
    'CRIMSON': '{HTML}{DC143C}',
    'CYAN': '{HTML}{00FFFF}',
    'DARKBLUE': '{HTML}{00008B}',
    'DARKCYAN': '{HTML}{008B8B}',
    'DARKGOLDENROD': '{HTML}{B8860B}',
    'DARKGRAY': '{HTML}{A9A9A9}',
    'DARKGREEN': '{HTML}{006400}',
    'DARKKHAKI': '{HTML}{BDB76B}',
    'DARKMAGENTA': '{HTML}{8B008B}',
    'DARKOLIVEGREEN': '{HTML}{556B2F}',
    'DARKORANGE': '{HTML}{FF8C00}',
    'DARKORCHID': '{HTML}{9932CC}',
    'DARKRED': '{HTML}{8B0000}',
    'DARKSALMON': '{HTML}{E9967A}',
    'DARKSEAGREEN': '{HTML}{8FBC8F}',
    'DARKSLATEBLUE': '{HTML}{483D8B}',
    'DARKSLATEGRAY': '{HTML}{2F4F4F}',
    'DARKTURQUOISE': '{HTML}{00CED1}',
    'DARKVIOLET': '{HTML}{9400D3}',
    'DEEPPINK': '{HTML}{FF1493}',
    'DEEPSKYBLUE': '{HTML}{00BFFF}',
    'DIMGRAY': '{HTML}{696969}',
    'DODGERBLUE': '{HTML}{1E90FF}',
    'FIREBRICK': '{HTML}{B22222}',
    'FLORALWHITE': '{HTML}{FFFAF0}',
    'FORESTGREEN': '{HTML}{228B22}',
    'FUCHSIA': '{HTML}{FF00FF}',
    'GAINSBORO': '{HTML}{DCDCDC}',
    'GHOSTWHITE': '{HTML}{F8F8FF}',
    'GOLD': '{HTML}{FFD700}',
    'GOLDENROD': '{HTML}{DAA520}',
    'GRAY': '{HTML}{808080}',
    'GREEN': '{HTML}{008000}',
    'GREENYELLOW': '{HTML}{ADFF2F}',
    'HONEYDEW': '{HTML}{F0FFF0}',
    'HOTPINK': '{HTML}{FF69B4}',
    'INDIANRED': '{HTML}{CD5C5C}',
    'INDIGO': '{HTML}{4B0082}',
    'IVORY': '{HTML}{FFFFF0}',
    'KHAKI': '{HTML}{F0E68C}',
    'LAVENDER': '{HTML}{E6E6FA}',
    'LAVENDERBLUSH': '{HTML}{FFF0F5}',
    'LAWNGREEN': '{HTML}{7CFC00}',
    'LEMONCHIFFON': '{HTML}{FFFACD}',
    'LIGHTBLUE': '{HTML}{ADD8E6}',
    'LIGHTCORAL': '{HTML}{F08080}',
    'LIGHTCYAN': '{HTML}{E0FFFF}',
    'LIGHTGOLDENRODYELLOW': '{HTML}{FAFAD2}',
    'LIGHTGRAY': '{HTML}{D3D3D3}',
    'LIGHTGREEN': '{HTML}{90EE90}',
    'LIGHTPINK': '{HTML}{FFB6C1}',
    'LIGHTSALMON': '{HTML}{FFA07A}',
    'LIGHTSEAGREEN': '{HTML}{20B2AA}',
    'LIGHTSKYBLUE': '{HTML}{87CEFA}',
    'LIGHTSLATEGRAY': '{HTML}{778899}',
    'LIGHTSTEELBLUE': '{HTML}{B0C4DE}',
    'LIGHTYELLOW': '{HTML}{FFFFE0}',
    'LIME': '{HTML}{00FF00}',
    'LIMEGREEN': '{HTML}{32CD32}',
    'LINEN': '{HTML}{FAF0E6}',
    'MAGENTA': '{HTML}{FF00FF}',
    'MAROON': '{HTML}{800000}',
    'MEDIUMAQUAMARINE': '{HTML}{66CDAA}',
    'MEDIUMBLUE': '{HTML}{0000CD}',
    'MEDIUMORCHID': '{HTML}{BA55D3}',
    'MEDIUMPURPLE': '{HTML}{9370DB}',
    'MEDIUMSEAGREEN': '{HTML}{3CB371}',
    'MEDIUMSLATEBLUE': '{HTML}{7B68EE}',
    'MEDIUMSPRINGGREEN': '{HTML}{00FA9A}',
    'MEDIUMTURQUOISE': '{HTML}{48D1CC}',
    'MEDIUMVIOLETRED': '{HTML}{C71585}',
    'MIDNIGHTBLUE': '{HTML}{191970}',
    'MINTCREAM': '{HTML}{F5FFFA}',
    'MISTYROSE': '{HTML}{FFE4E1}',
    'MOCCASIN': '{HTML}{FFE4B5}',
    'NAVAJOWHITE': '{HTML}{FFDEAD}',
    'NAVY': '{HTML}{000080}',
    'OLDLACE': '{HTML}{FDF5E6}',
    'OLIVE': '{HTML}{808000}',
    'OLIVEDRAB': '{HTML}{6B8E23}',
    'ORANGE': '{HTML}{FFA500}',
    'ORANGERED': '{HTML}{FF4500}',
    'ORCHID': '{HTML}{DA70D6}',
    'PALEGOLDENROD': '{HTML}{EEE8AA}',
    'PALEGREEN': '{HTML}{98FB98}',
    'PALETURQUOISE': '{HTML}{AFEEEE}',
    'PALEVIOLETRED': '{HTML}{DB7093}',
    'PAPAYAWHIP': '{HTML}{FFEFD5}',
    'PEACHPUFF': '{HTML}{FFDAB9}',
    'PERU': '{HTML}{CD853F}',
    'PINK': '{HTML}{FFC0CB}',
    'PLUM': '{HTML}{DDA0DD}',
    'POWDERBLUE': '{HTML}{B0E0E6}',
    'PURPLE': '{HTML}{800080}',
    'RED': '{HTML}{FF0000}',
    'ROSYBROWN': '{HTML}{BC8F8F}',
    'ROYALBLUE': '{HTML}{4169E1}',
    'SADDLEBROWN': '{HTML}{8B4513}',
    'SALMON': '{HTML}{FA8072}',
    'SANDYBROWN': '{HTML}{F4A460}',
    'SEAGREEN': '{HTML}{2E8B57}',
    'SEASHELL': '{HTML}{FFF5EE}',
    'SIENNA': '{HTML}{A0522D}',
    'SILVER': '{HTML}{C0C0C0}',
    'SKYBLUE': '{HTML}{87CEEB}',
    'SLATEBLUE': '{HTML}{6A5ACD}',
    'SLATEGRAY': '{HTML}{708090}',
    'SNOW': '{HTML}{FFFAFA}',
    'SPRINGGREEN': '{HTML}{00FF7F}',
    'STEELBLUE': '{HTML}{4682B4}',
    'TAN': '{HTML}{D2B48C}',
    'TEAL': '{HTML}{008080}',
    'THISTLE': '{HTML}{D8BFD8}',
    'TOMATO': '{HTML}{FF6347}',
    'TURQUOISE': '{HTML}{40E0D0}',
    'VIOLET': '{HTML}{EE82EE}',
    'WHEAT': '{HTML}{F5DEB3}',
    'WHITE': '{HTML}{FFFFFF}',
    'WHITESMOKE': '{HTML}{F5F5F5}',
    'YELLOW': '{HTML}{FFFF00}',
    'YELLOWGREEN': '{HTML}{9ACD32}',
}


#не стоит добавлять такие вещи, как sin, т.к в таком случае слово apelsin будет выглядеть странно
plain_to_tex_dict = {
    u'#': ur'$\#$',
    u'%': ur'$\%$',
    u'{': ur'$\{$',
    u'}': ur'$\}$',
    u'$': ur'$\$$',
    u'&': ur'$\&$',
    u'_': ur'$\_$',
    u'\\': ur'$\backslash$',
    u'<=': ur'$\leqslant$',
    u'>=': ur'$\geqslant$',
    u'^': ur'{\string^}',
    u'&nbsp;': ur'{ }',
    u'&lt;': ur'<',
    u'&gt;': ur'>',
    u'&mdash;': ur'---',
    u'&amp;': ur'$\&$',
    u'&#169;': ur'{\copyright}',
    u'&copy;': ur'{\copyright}',
    u'&#39;': u'{\'}',
    u'\'': u'{\'}',
    u'&ndash;': ur'-',
    u'&#33;': ur')',
    u'&#8593;': u'$\\uparrow$',
    u'&#8595;': u'$\\downarrow$',
    u'&quot;': ur"{\textquotedbl}",
    u'...': ur'\ldots',
    u'"': ur"{\textquotedbl}",
}


ordered_stylenames_list = [
    u"font-size",
    u"sub",
    u"sup",
    u"text-decoration",
    u"font-style",
    u"font-weight",
    u"text-background-color",
    u"color",
    u"other",
]


style_sorting_weight = {}

for pos in xrange(len(ordered_stylenames_list)):
    style_sorting_weight[ordered_stylenames_list[pos]] = pos




empty_mdframed_begin = u"\\begin{mdframed}[skipabove=0, skipbelow=0, innerleftmargin=0, innerrightmargin=0, linewidth=0"